apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-keys
  description: Simple Node.js API with API Key Management
  tags:
    - rest-api
    - express
  annotations:
    harness.io/flows-action: api-key-vending  
  links:
    - url: https://github.com/harness-tr/api-keys
      title: GitHub Repo
      icon: github
    - url: https://github.com/harness-tr/api-keys/blob/main/api-keys.oas.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  owner: group:default/technologyproduct_engineering
  lifecycle: experimental
  definition:
    $text: ./api-keys.oas.yaml
